### ISSUE TITLE
Exception: hparams.yaml file is missing!

### ISSUE THREAD

**Issue by DennisDavari** [Yao-Dou/LENS#15]
Hello, when I want to do a test run I always get the error message "Exception: hparams.yaml file is missing!". It doesn't matter if I only use the ckpt file or the whole LENSE folder in the file path. This is the error message which I am getting:

`"G:\My Drive\M5\Masterarbeit\implementation_metrics\LENS\venv\Scripts\python.exe" "G:\My Drive\M5\Masterarbeit\implementation_metrics\LENS\run-dennis.py" 
Traceback (most recent call last):
  File "G:\My Drive\M5\Masterarbeit\implementation_metrics\LENS\run-dennis.py", line 8, in <module>
    metric = LENS(model_path, rescale=True)
  File "G:\My Drive\M5\Masterarbeit\implementation_metrics\LENS\venv\lib\site-packages\lens\lens_score.py", line 9, in __init__
    self.model = load_from_checkpoint(path)
  File "G:\My Drive\M5\Masterarbeit\implementation_metrics\LENS\venv\lib\site-packages\lens\models\__init__.py", line 46, in load_from_checkpoint
    raise Exception("hparams.yaml file is missing!")
Exception: hparams.yaml file is missing!

Process finished with exit code 1`

I am using Windows 11 and for this project I use Python 3.7 on a PyCharm virtual environment.

Thank you in advance!

**Comment by Yao-Dou** [comment]
Hello, here is the code `load_from_checkpoint` function in the [models__init__.py](https://github.com/Yao-Dou/LENS/blob/master/lens/lens/models/__init__.py)
<pre>
    <b>hparams_file = "/".join(checkpoint_path.split("/")[:-2] + ["hparams.yaml"])</b>
    if os.path.exists(hparams_file):
        with open(hparams_file) as yaml_file:
            hparams = yaml.load(yaml_file.read(), Loader=yaml.FullLoader)
        model_class = str2model[hparams["class_identifier"]]
        model = model_class.load_from_checkpoint(checkpoint_path, **hparams)
        return model
    else:
        raise Exception("hparams.yaml file is missing!")
</pre>
here the `checkpoint_path` is the `model_path` that you provide, so if the model path is `a/model.ckpt` then hparams.yaml should be at `hparams.yaml` instead of `a/hparams.yaml`. If your `hparams.yaml` is in the `a` folder, you can either move it outside `a` or change the -2 to -1 in `hparams_file = "/".join(checkpoint_path.split("/")[:-2] + ["hparams.yaml"])` (line 38 of models__init__.py).

**Comment by DennisDavari** [comment]
Thank you for explanation! Now it works. The problem was that I used '\' instead of '/' when referring to the file path.
